--- @meta
---
--- 999s Developer - Types of Bridge
--- Made for developing script eaiser and readable
--- @github mysbryce
--- @portfolio https://stateless-prt.vercel.app
--- @email fx.frame009@gmail.com
--- 
---

--- @class EventObject
--- @field name EventName
--- @field paramsSort EventParamsSort
---
---
--- @class EventContext
--- @field get fun(key: string): any
--- 
--- 
--- @class SchemaFallback
--- @field makeTypes fun(typesList: EventParamsType): SchemaFallback
--- @field registerAs fun(key: string): SchemaFallback
--- @field getSchema fun(): EventObject
--- 
--- @class ArrayPrototype
--- @field len fun(self: ArrayPrototype): integer
--- @field push fun(self: ArrayPrototype, value: any)
--- @field pop fun(self: ArrayPrototype): any
--- @field shift fun(self: ArrayPrototype): any
--- @field unshift fun(self: ArrayPrototype, value: any)
--- @field forEach fun(self: ArrayPrototype, callback: fun(value: any, index: integer))
--- @field map fun(self: ArrayPrototype, callback: fun(value: any, index: integer): any): ArrayPrototype
--- @field filter fun(self: ArrayPrototype, callback: fun(value: any, index: integer): boolean): ArrayPrototype
--- @field find fun(self: ArrayPrototype, callback: fun(value: any, index: integer): boolean): any
--- @field includes fun(self: ArrayPrototype, value: any): boolean
--- @field indexOf fun(self: ArrayPrototype, value: any): integer
--- @field toTable fun(self: ArrayPrototype): any[]
--- @field print fun(self: ArrayPrototype)
---
--- @alias StateFallbackGet fun(): any
--- @alias StateFallbackSet fun(newValue: any)
--- @alias StateCallback fun(previousValue: any, newValue: any)
--- @alias EventCallback fun(ctx: EventContext)
--- @alias EventName string | string[]
--- @alias EventParamsSort table<string, number>
--- @alias EventParamsType table<string, VarType>
--- @alias DebugType 'success' | 'info' | 'warn' | 'error'
--- @alias VarType 'nil' | 'number' | 'string' | 'boolean' | 'table' | 'function' | 'thread' | 'userdata' | null
--- @alias null 'NULL'